// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using our_project.Models;

namespace our_project.Migrations
{
    [DbContext(typeof(UnemploymentContext))]
    [Migration("20190424180258_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("our_project.Models.UnemploymentStat", b =>
                {
                    b.Property<int>("InstanceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("County");

                    b.Property<int>("CountyCode");

                    b.Property<int>("Employed");

                    b.Property<int>("Force");

                    b.Property<string>("State");

                    b.Property<int>("StateCode");

                    b.Property<int>("Unemployed");

                    b.Property<float>("UnemploymentRate");

                    b.Property<int>("Year");

                    b.HasKey("InstanceId");

                    b.ToTable("UnemploymentStats");
                });
#pragma warning restore 612, 618
        }
    }
}
